site_name: "bindED VoiceAttack plugin"
site_url: https://alterNERDtive.github.io/YAVAPF
repo_url: https://github.com/alterNERDtive/YAVAPF
edit_uri: "edit/devel/docs/"
site_description: "YAVAPF is yet another VoiceAttack plugin framework."
site_author: "alterNERDtive"
remote_name: "origin"

theme:
    name: readthedocs
    prev_next_buttons_location: both

plugins:
    - search
    - roamlinks

markdown_extensions:
    - toc:
        permalink: True
    - sane_lists

nav:
    - 'Home': 'index.md'
    - 'Usage':
        - 'Getting Started': 'gettingstarted.md'
        - 'Event Handlers': 'events.md'
        - 'Plugin Contexts': 'contexts.md'
        - 'Working with Variables': 'variables.md'
        - 'Running Commands': 'commands.md'
    - 'troubleshooting.md'
    - '⎋ Changelog': 'https://github.com/alterNERDtive/YAVAPF/blob/release/CHANGELOG.md'
    - '⎋ Report a Bug': 'https://github.com/alterNERDtive/YAVAPF/issues/'
