site_name: "YAVAPF – Yet Another VoiceAttack Plugin Framework"
site_url: https://alterNERDtive.github.io/YAVAPF
repo_url: https://github.com/alterNERDtive/YAVAPF
edit_uri: "edit/devel/docs/"
site_description: "YAVAPF is yet another VoiceAttack plugin framework."
site_author: "alterNERDtive"
remote_name: "origin"

extra_css: [extra.css]

theme:
    name: readthedocs
    prev_next_buttons_location: both

plugins:
    - search
    - roamlinks

markdown_extensions:
    - toc:
        permalink: True
    - sane_lists
    - pymdownx.tasklist

nav:
    - 'Home': 'index.md'
    - 'Usage':
        - 'gettingstarted.md'
        - 'events.md'
        - 'contexts.md'
        - 'variables.md'
        - 'commands.md'
        - 'logging.md'
    - Troubleshooting:
        - 'faq.md'
    - '⎋ Changelog': 'https://github.com/alterNERDtive/YAVAPF/blob/release/CHANGELOG.md'
    - '⎋ Report a Bug': 'https://github.com/alterNERDtive/YAVAPF/issues/'
