//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace alterNERDtive.Yavapf {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class L10n {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal L10n() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("alterNERDtive.Yavapf.L10n", typeof(L10n).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error setting log level: &apos;{0}&apos; is not a valid log level..
        /// </summary>
        internal static string ErrorSettingLogLevel {
            get {
                return ResourceManager.GetString("ErrorSettingLogLevel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Finished running Init handlers..
        /// </summary>
        internal static string FinishedRunningInitHandlers {
            get {
                return ResourceManager.GetString("FinishedRunningInitHandlers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Initialized..
        /// </summary>
        internal static string Initialized {
            get {
                return ResourceManager.GetString("Initialized", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid plugin context &apos;{0}&apos;..
        /// </summary>
        internal static string InvalidPluginContext {
            get {
                return ResourceManager.GetString("InvalidPluginContext", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Missing parameter &apos;{0}&apos; for context &apos;{1}&apos;..
        /// </summary>
        internal static string MissingParameterForContext {
            get {
                return ResourceManager.GetString("MissingParameterForContext", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Initializing v{0} ….
        /// </summary>
        internal static string PluginInitializing {
            get {
                return ResourceManager.GetString("PluginInitializing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Running Init handlers ….
        /// </summary>
        internal static string RunningInitHandlers {
            get {
                return ResourceManager.GetString("RunningInitHandlers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unhandled exception while executing plugin context &apos;{0}&apos;: {1}.
        /// </summary>
        internal static string UnhandledExceptionWhileExecutingPluginContext {
            get {
                return ResourceManager.GetString("UnhandledExceptionWhileExecutingPluginContext", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unhandled exception while handling changed {0} variable &apos;{1}&apos;: {2}.
        /// </summary>
        internal static string UnhandledExceptionWhileHandlingChangedVariable {
            get {
                return ResourceManager.GetString("UnhandledExceptionWhileHandlingChangedVariable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Accessing command scoped variable &apos;{0}&apos; outside of its context proxy object. This might lead to race conditions..
        /// </summary>
        internal static string WarningCommandScopedVariable {
            get {
                return ResourceManager.GetString("WarningCommandScopedVariable", resourceCulture);
            }
        }
    }
}
