name: Run tests on push

on:
  push

jobs:
  build:
    name: Run tests
    runs-on: windows-latest
    permissions:
      contents: write

    steps:
      - name: Install VoiceAttack
        run: |
          curl.exe -o VoiceAttackSetup.exe https://voiceattack.com/FileSend.aspx?id=VoiceAttackInstaller64.exe
          .\VoiceAttackSetup /sp- /verysilent /suppressmsgboxes /norestart /nocloseapplications /norestartapplications /noicons

      - name: Checkout source code
        uses: actions/checkout@v2

      - name: Setup .Net
        uses: actions/setup-dotnet@v2
        with:
          dotnet-version: '6.0.x'

      - name: Restore dependencies
        run: dotnet restore

      - name: Build
        run: dotnet build -c release

      - name: Run tests
        run: dotnet test
